from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton, WebAppInfo
from aiogram.utils.keyboard import InlineKeyboardBuilder

inline_kb_full = InlineKeyboardBuilder()
bl_1 = InlineKeyboardButton(text='1', callback_data='btn1')
bl_2 = InlineKeyboardButton(text='2', callback_data='btn2')
bl_3 = InlineKeyboardButton(text='3', callback_data='btn3')
bl_4 = InlineKeyboardButton(text='4', callback_data='btn4')
bl_5 = InlineKeyboardButton(text='5', callback_data='btn5')
bl_6 = InlineKeyboardButton(text='6', callback_data='btn6')
bl_7 = InlineKeyboardButton(text='7', callback_data='btn7')
bl_8 = InlineKeyboardButton(text='8', callback_data='btn8')
bl_9 = InlineKeyboardButton(text='9', callback_data='btn9')
bl_10 = InlineKeyboardButton(text='10', callback_data='btn10')
bl_11 = InlineKeyboardButton(text='11', callback_data='btn11')
bl_12 = InlineKeyboardButton(text='12', callback_data='btn12')
bl_13 = InlineKeyboardButton(text='13', callback_data='btn13')
bl_14 = InlineKeyboardButton(text='14', callback_data='btn14')
bl_15 = InlineKeyboardButton(text='15', callback_data='btn15')
bl_16 = InlineKeyboardButton(text='16', callback_data='btn16')
bl_17 = InlineKeyboardButton(text='17', callback_data='btn17')
bl_18 = InlineKeyboardButton(text='18', callback_data='btn18')
bl_19 = InlineKeyboardButton(text='19', callback_data='btn19')
bl_20 = InlineKeyboardButton(text='20', callback_data='btn20')
inline_kb_full.add(bl_1, bl_2, bl_3, bl_4, bl_5, bl_6, bl_7, bl_8)
inline_kb_full = inline_kb_full.as_markup()